# Generated by Django 2.2.4 on 2019-12-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchaseorder', '0020_purchaseorder_internal_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='partialorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('internal_notes', models.TextField(default='')),
                ('is_tracking', models.BooleanField(default=True)),
                ('order_line_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.orderline')),
            ],
        ),
    ]
