# Generated by Django 2.2.4 on 2020-01-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0022_orderline_refund_resolved'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.TextField()),
                ('from_email', models.TextField()),
                ('message', models.TextField()),
                ('sent_date', models.TextField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.orderid_purchaseorderid')),
            ],
        ),
    ]
