# Generated by Django 2.2.4 on 2020-01-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_email_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_history',
            name='handler',
            field=models.TextField(default='Find Sports'),
        ),
    ]
