# Generated by Django 2.2.4 on 2019-09-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('uncommitted_date', models.DateField()),
                ('cancelled_date', models.DateField()),
            ],
        ),
    ]
