# Generated by Django 2.2.4 on 2019-11-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingDispatchOrderIDExceptions',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comments', models.TextField()),
            ],
        ),
    ]
