# Generated by Django 2.2.4 on 2019-11-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pendingdispatchorderidexceptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRefundsOrderIDExceptions',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comments', models.TextField()),
            ],
        ),
    ]
