# Generated by Django 2.2.4 on 2020-01-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0016_supplier_details_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockupdate',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('run_date', models.DateField()),
                ('run_status', models.CharField(max_length=50)),
                ('prev_instock', models.IntegerField()),
                ('new_instock', models.IntegerField()),
                ('stock_update_approved', models.BooleanField(default=False)),
                ('comments', models.TextField(null=True)),
                ('supplier_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier_Details')),
            ],
        ),
    ]
