# Generated by Django 2.2.4 on 2020-01-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_supplier_details_disabled'),
        ('stockupdate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockupdate',
            name='oos_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='stockupdate',
            name='time_taken',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockupdate',
            unique_together={('supplier_name', 'run_date')},
        ),
    ]
