# Generated by Django 2.2.4 on 2020-01-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupdate', '0002_auto_20200118_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupdate',
            name='new_instock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='prev_instock',
            field=models.IntegerField(null=True),
        ),
    ]
