# Generated by Django 2.2.4 on 2020-01-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_supplier_details_disabled'),
        ('stockupdate', '0003_auto_20200118_2002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockupdate',
            unique_together={('supplier_name', 'run_date', 'run_status')},
        ),
    ]
