# Generated by Django 2.2.4 on 2020-01-20 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_supplier_details_last_stock_update_filename'),
        ('stockupdate', '0005_stockupdate_disabled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockupdate',
            unique_together={('supplier_name', 'run_date', 'run_status', 'disabled')},
        ),
    ]
