# Generated by Django 2.2.4 on 2020-01-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockupdate', '0006_auto_20200120_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockupdate',
            name='potential_new_products',
            field=models.IntegerField(null=True),
        ),
    ]
