# Generated by Django 2.2.4 on 2020-02-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_supplier_details_last_stock_update_filename'),
        ('stockupdate', '0007_stockupdate_potential_new_products'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockupdate',
            unique_together={('supplier_name', 'run_date', 'run_status', 'disabled', 'prev_instock', 'new_instock')},
        ),
    ]
