# Generated by Django 2.2.4 on 2019-10-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='refunds',
            fields=[
                ('OrderLineID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('OrderID', models.CharField(max_length=100)),
                ('Emailed', models.TextField()),
                ('Reason', models.TextField()),
                ('DateRequested', models.DateField()),
                ('BillFirstName', models.TextField()),
                ('BillLastName', models.TextField()),
                ('PaymentMethod', models.TextField()),
                ('AmountPaid', models.IntegerField(max_length=10)),
                ('DateInvoiced', models.DateField()),
            ],
        ),
    ]
