# Generated by Django 2.2.4 on 2019-10-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refunds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunds',
            name='AmountPaid',
            field=models.IntegerField(),
        ),
    ]
