# Generated by Django 2.2.4 on 2019-12-30 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchaseorder', '0020_purchaseorder_internal_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='escalatedorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_notes', models.TextField(null=True)),
                ('handler', models.CharField(max_length=100)),
                ('open', models.BooleanField(default=False)),
                ('refund', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
                ('history', models.TextField(null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.orderid_purchaseorderid')),
            ],
        ),
    ]
