# Generated by Django 2.2.4 on 2019-12-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalatedorders',
            name='refund',
        ),
        migrations.RemoveField(
            model_name='escalatedorders',
            name='resolved',
        ),
        migrations.AddField(
            model_name='escalatedorders',
            name='priority',
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escalatedorders',
            name='status',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escalatedorders',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
