# Generated by Django 2.2.4 on 2019-12-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0002_auto_20191230_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalatedorders',
            name='id',
        ),
        migrations.AlterField(
            model_name='escalatedorders',
            name='order_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
