# Generated by Django 2.2.4 on 2019-12-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0003_auto_20191230_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalatedorders',
            name='zendeskticket',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
