# Generated by Django 2.2.4 on 2020-01-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0004_escalatedorders_zendeskticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalatedorders',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
