# Generated by Django 2.2.4 on 2020-01-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0006_customer_service_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalatedorders',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escalatedorders.customer_service_users'),
        ),
    ]
