# Generated by Django 2.2.4 on 2020-01-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0007_escalatedorders_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalatedorders',
            name='name',
        ),
        migrations.DeleteModel(
            name='customer_service_users',
        ),
    ]
