# Generated by Django 2.2.4 on 2020-01-09 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0008_auto_20200109_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_service_users',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='escalatedorders',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escalatedorders.customer_service_users'),
        ),
    ]
