# Generated by Django 2.2.4 on 2020-01-09 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0011_auto_20200109_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='zendesk_locked_tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zendeskticket', models.CharField(max_length=100)),
                ('locked', models.BooleanField(default=True)),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escalatedorders.customer_service_users')),
            ],
        ),
    ]
