# Generated by Django 2.2.4 on 2020-01-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0012_zendesk_locked_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='independentescalatedtickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_notes', models.TextField(null=True)),
                ('handler', models.CharField(max_length=100)),
                ('priority', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('open', models.BooleanField(default=False)),
                ('zendeskticket', models.CharField(max_length=20, null=True)),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escalatedorders.customer_service_users')),
            ],
        ),
    ]
