# Generated by Django 2.2.4 on 2020-01-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0013_independentescalatedtickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independentescalatedtickets',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
