# Generated by Django 2.2.4 on 2020-01-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0014_auto_20200116_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='independentescalatedtickets',
            name='created_date',
            field=models.DateField(null=True),
        ),
    ]
