# Generated by Django 2.2.4 on 2020-01-22 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0016_auto_20200122_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalatedorders',
            name='resolved_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='independentescalatedtickets',
            name='resolved_date',
            field=models.DateField(null=True),
        ),
    ]
