# Generated by Django 2.2.4 on 2020-01-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0017_auto_20200122_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalatedorders',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='escalatedorders',
            name='resolved_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='independentescalatedtickets',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='independentescalatedtickets',
            name='resolved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
