# Generated by Django 2.2.4 on 2020-01-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0018_auto_20200122_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalatedorders',
            name='created_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='escalatedorders',
            name='resolved_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='independentescalatedtickets',
            name='created_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='independentescalatedtickets',
            name='resolved_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
