# Generated by Django 2.2.4 on 2020-01-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0019_auto_20200122_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_service_users',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
