# Generated by Django 2.2.4 on 2020-01-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0020_customer_service_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalatedorders',
            name='last_updated_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
