# Generated by Django 2.2.4 on 2020-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0021_escalatedorders_last_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_service_users',
            name='escalation_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer_service_users',
            name='task_permission',
            field=models.BooleanField(default=False),
        ),
    ]
