# Generated by Django 2.2.4 on 2019-12-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebomb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timebomb',
            name='id',
        ),
        migrations.AlterField(
            model_name='timebomb',
            name='sku',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
