# Generated by Django 2.2.4 on 2019-12-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebomb', '0003_remove_timebomb_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebomb',
            name='promotion_expiry',
            field=models.CharField(max_length=50),
        ),
    ]
