# Generated by Django 2.2.4 on 2019-12-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timebomb', '0004_auto_20191229_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timebomb',
        ),
    ]
