# Generated by Django 2.2.4 on 2019-12-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timebomb', '0005_delete_timebomb'),
    ]

    operations = [
        migrations.CreateModel(
            name='timebomb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=15)),
                ('promotion_expiry', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('sku', 'day')},
            },
        ),
    ]
