# Generated by Django 2.2.4 on 2019-10-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='sales_channel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
