# Generated by Django 2.2.4 on 2019-10-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customers_sales_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='date_invoiced',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='date_shipped',
        ),
    ]
