# Generated by Django 2.2.4 on 2019-09-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=100)),
                ('update_date', models.DateField(null=True)),
            ],
        ),
    ]
