# Generated by Django 2.2.4 on 2019-09-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='update_date',
            new_name='Backorder_Approved',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_status',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='Cancelled',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='Dispatched',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='New',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='New_Backorder',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='On_Hold',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='Pack',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='Pending_Dispatch',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='Pending_Pickup',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='Pick',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='Quote',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='Uncommitted',
            field=models.DateField(null=True),
        ),
    ]
