# Generated by Django 2.2.4 on 2019-09-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0002_auto_20190925_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='shipped_date',
            field=models.DateField(null=True),
        ),
    ]
