# Generated by Django 2.2.4 on 2019-09-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0003_orderhistory_shipped_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
