# Generated by Django 2.2.4 on 2019-09-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0004_auto_20190926_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='invoice_date',
            field=models.DateField(null=True),
        ),
    ]
