# Generated by Django 2.2.4 on 2019-09-29 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0005_orderhistory_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
