# Generated by Django 2.2.4 on 2019-09-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0006_auto_20190929_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='sales_channel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
