# Generated by Django 2.2.4 on 2019-09-30 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0007_orderhistory_sales_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='sales_channel',
        ),
    ]
