# Generated by Django 2.2.4 on 2019-10-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0008_remove_orderhistory_sales_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='delayed',
            field=models.BooleanField(default=False),
        ),
    ]
