# Generated by Django 2.2.4 on 2019-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0009_orderhistory_delayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='test_col',
            field=models.BooleanField(null=True),
        ),
    ]
