# Generated by Django 2.2.4 on 2019-10-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0010_orderhistory_test_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='test_col',
        ),
    ]
