# Generated by Django 2.2.4 on 2020-01-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoapihook', '0012_orderhistory_sales_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='is_dropshipped',
            field=models.BooleanField(default=False),
        ),
    ]
