# Generated by Django 2.2.4 on 2019-10-24 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0010_suppliernew'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseorder',
            fields=[
                ('purchase_orderid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_date', models.DateField()),
                ('tracking_id', models.CharField(max_length=100, null=True)),
                ('courier', models.CharField(max_length=100, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_date', models.DateField(null=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('supplier_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.Supplier_Details')),
            ],
        ),
        migrations.CreateModel(
            name='purchaseorder_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField()),
                ('qty', models.TextField()),
                ('order_line_id', models.TextField()),
                ('instock', models.TextField()),
                ('part_number', models.TextField()),
                ('purchase_orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='orderid_purchaseorderid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('sku', models.TextField()),
                ('order_line_id', models.CharField(max_length=100)),
                ('purchase_orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.purchaseorder')),
            ],
            options={
                'unique_together': {('order_id', 'order_line_id', 'purchase_orderid', 'sku')},
            },
        ),
    ]
