# Generated by Django 2.2.4 on 2019-10-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='stock_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
