# Generated by Django 2.2.4 on 2019-10-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0002_purchaseorder_stock_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_line_id', models.TextField()),
                ('sku', models.TextField()),
                ('part_number', models.TextField()),
                ('qty', models.TextField()),
                ('instock', models.TextField()),
                ('purchase_orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.purchaseorder')),
            ],
        ),
    ]
