# Generated by Django 2.2.4 on 2019-10-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0003_orderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order_line_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
