# Generated by Django 2.2.4 on 2019-10-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0005_auto_20191029_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='legacy_purchase_id',
            field=models.BooleanField(default=True),
        ),
    ]
