# Generated by Django 2.2.4 on 2019-10-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0006_purchaseorder_legacy_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='legacy_purchase_id',
            field=models.BooleanField(default=False),
        ),
    ]
