# Generated by Django 2.2.4 on 2019-10-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0007_auto_20191029_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderid_purchaseorderid',
            name='sku',
            field=models.TextField(null=True),
        ),
    ]
