# Generated by Django 2.2.4 on 2019-11-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0008_auto_20191029_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='dropship',
            field=models.BooleanField(default=False),
        ),
    ]
