# Generated by Django 2.2.4 on 2019-11-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0009_orderline_dropship'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_purchaseorder',
            fields=[
                ('sub_purchaseorderid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_date', models.DateField()),
                ('tracking_id', models.CharField(max_length=100, null=True)),
                ('courier', models.CharField(max_length=100, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('stock_confirmed', models.BooleanField(default=False)),
                ('submitted_date', models.DateField(null=True)),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('purchase_orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.purchaseorder')),
            ],
        ),
    ]
