# Generated by Django 2.2.4 on 2019-11-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0010_sub_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_purchaseorder',
            name='created_date',
        ),
        migrations.AddField(
            model_name='orderline',
            name='sub_purchaseorderid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseorder.sub_purchaseorder'),
        ),
    ]
