# Generated by Django 2.2.4 on 2019-11-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0011_auto_20191108_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
