# Generated by Django 2.2.4 on 2019-11-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0014_auto_20191114_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='received_date',
        ),
    ]
