# Generated by Django 2.2.4 on 2019-12-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0018_purchaseorder_internal_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='internal_notes',
        ),
    ]
