# Generated by Django 2.2.4 on 2020-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0020_purchaseorder_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='available_in_store',
            field=models.BooleanField(default=False),
        ),
    ]
