# Generated by Django 2.2.4 on 2020-01-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorder', '0021_orderline_available_in_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='refund_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
