# Generated by Django 2.2.4 on 2019-10-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sku', models.TextField()),
                ('primarysupplier', models.TextField()),
            ],
        ),
    ]
