# Generated by Django 2.2.4 on 2019-10-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_email', models.CharField(max_length=300)),
                ('minimum_stock', models.CharField(max_length=100, null=True)),
                ('website_name', models.CharField(max_length=100, null=True)),
                ('website_link', models.TextField(null=True)),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('pass_word', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
