# Generated by Django 2.2.4 on 2019-10-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier_details',
            old_name='minimum_stock',
            new_name='minimum_order',
        ),
        migrations.RenameField(
            model_name='supplier_details',
            old_name='pass_word',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='supplier_details',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='supplier_details',
            name='supplier_email',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
