# Generated by Django 2.2.4 on 2019-10-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_auto_20191010_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_details',
            name='supplier_email',
            field=models.CharField(default='NA', max_length=300),
        ),
    ]
