# Generated by Django 2.2.4 on 2019-10-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_auto_20191010_0551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_details',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplier_details',
            name='supplier_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
