# Generated by Django 2.2.4 on 2019-10-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_auto_20191010_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_details',
            name='short_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
