# Generated by Django 2.2.4 on 2019-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_supplier_details_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='purchase_order_generated',
            field=models.BooleanField(default=False),
        ),
    ]
