# Generated by Django 2.2.4 on 2019-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_supplier_purchase_order_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_details',
            name='onhold',
            field=models.BooleanField(default=False),
        ),
    ]
