# Generated by Django 2.2.4 on 2019-10-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_supplier_details_onhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_details',
            name='onhold_date',
            field=models.DateField(null=True),
        ),
    ]
