# Generated by Django 2.2.4 on 2019-10-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_supplier_details_onhold_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierNew',
            fields=[
                ('order_line_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=100)),
                ('sku', models.TextField()),
                ('primarysupplier', models.TextField()),
                ('purchase_order_generated', models.BooleanField(default=False)),
            ],
        ),
    ]
