# Generated by Django 2.2.4 on 2019-10-25 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_suppliernew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
