# Generated by Django 2.2.4 on 2019-10-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_supplier_details_website_order_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliernew',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
