# Generated by Django 2.2.4 on 2019-11-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_auto_20191115_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliernew',
            name='reorder',
            field=models.BooleanField(default=False),
        ),
    ]
