# Generated by Django 2.2.4 on 2020-01-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0016_supplier_details_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_details',
            name='last_stock_update',
            field=models.DateField(null=True),
        ),
    ]
