# Generated by Django 2.2.4 on 2020-01-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0017_supplier_details_last_stock_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_details',
            name='last_stock_update_filename',
            field=models.TextField(null=True),
        ),
    ]
