# Generated by Django 2.2.4 on 2020-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_supplier_details_last_stock_update_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_details',
            name='stock_take_automated',
            field=models.BooleanField(default=False),
        ),
    ]
