# Generated by Django 2.2.4 on 2020-01-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sku', models.CharField(max_length=100, null=True)),
                ('product_description', models.TextField(null=True)),
                ('product_link', models.TextField(null=True)),
                ('product_image_link', models.TextField(null=True)),
                ('product_alias', models.CharField(max_length=100)),
            ],
        ),
    ]
