# Generated by Django 2.2.4 on 2020-01-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='product_type',
            field=models.CharField(default='product', max_length=100, null=True),
        ),
    ]
