# Generated by Django 2.2.4 on 2020-01-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='product_height',
            field=models.CharField(default='209', max_length=5),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='product_width',
            field=models.CharField(default='314', max_length=5),
        ),
    ]
