# Generated by Django 2.2.4 on 2020-01-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_auto_20200105_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='product_price_starting_from',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
