# Generated by Django 2.2.4 on 2020-01-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_product_price_starting_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='product_row',
            field=models.IntegerField(null=True),
        ),
    ]
