# Generated by Django 2.2.4 on 2020-01-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_newsletter_product_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='product_height',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='product_width',
            field=models.CharField(max_length=5),
        ),
    ]
