# Generated by Django 2.2.4 on 2020-02-12 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escalatedorders', '0021_escalatedorders_last_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasklist',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_description', models.TextField(null=True)),
                ('task_priority', models.IntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('history', models.TextField(null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalatedorders.customer_service_users')),
            ],
        ),
    ]
