# Generated by Django 2.2.4 on 2020-02-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0004_auto_20200216_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_task',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
