# Generated by Django 2.2.4 on 2020-02-16 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0006_remove_tasklist_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'permissions': [('all_tasks_access', 'Has access to all tasks'), ('all_regular_tasks_access', 'Has access to all regular tasks')]},
        ),
    ]
