# Generated by Django 2.2.4 on 2020-02-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0023_auto_20200216_2331'),
        ('tasklist', '0007_auto_20200216_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField(null=True)),
                ('private', models.BooleanField(default=True)),
                ('group_status', models.BooleanField(default=True)),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='escalatedorders.customer_service_users')),
            ],
            options={
                'unique_together': {('group_id', 'name')},
            },
        ),
        migrations.AddField(
            model_name='tasklist',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasklist.task_groups'),
        ),
    ]
