# Generated by Django 2.2.4 on 2020-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0009_remove_task_groups_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
