# Generated by Django 2.2.4 on 2020-02-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0011_tasklist_extension_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurring_task',
            name='last_updated_date',
            field=models.DateField(null=True),
        ),
    ]
