# Generated by Django 2.2.4 on 2020-02-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalatedorders', '0023_auto_20200216_2331'),
        ('tasklist', '0012_recurring_task_last_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='recurring_task_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateField(null=True)),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='escalatedorders.customer_service_users')),
                ('task_id', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='tasklist.tasklist')),
            ],
            options={
                'unique_together': {('task_id', 'name', 'updated_date')},
            },
        ),
    ]
